// Cloudflare Workers entry point. Opt-in; Vercel and Docker never load this.
//
// OpenNext generates `.open-next/worker.js` with a `fetch` handler and nothing
// else. Cron Triggers call `scheduled`, so this wraps the generated handler and
// adds one. It is plain JavaScript rather than TypeScript so that `next build`,
// whose type-check includes every .ts file under apps/web, never sees it.
//
// Each Cron Trigger in wrangler.jsonc is one of the nine schedules in
// vercel.json. `controller.cron` carries the expression that fired, and this map
// turns it back into the route the scheduler on Vercel would have called. The
// routes keep their own auth (`x-cron-secret`), so the Worker needs the same
// CRON_SECRET the routes compare against, as a Worker secret.

// Generated by `opennextjs-cloudflare build`; absent until then.
import handler from "../.open-next/worker.js";

const CRON_ROUTES = {
  "0 2 * * *": "/api/cron/analyze",
  "0 3 * * *": "/api/cron/serp",
  "20 3 * * *": "/api/cron/serp-collect",
  "0 4 * * *": "/api/cron/analytics",
  "0 5 * * *": "/api/cron/exchange",
  "0 6 1 * *": "/api/cron/reports",
  "0 7 * * *": "/api/cron/generate",
  "0 8 * * 1": "/api/cron/geo",
  "0 9 * * *": "/api/cron/publish",
};

const worker = {
  fetch: handler.fetch,

  async scheduled(controller, env) {
    const path = CRON_ROUTES[controller.cron];
    if (!path) {
      console.error(`cron: no route for schedule "${controller.cron}"; check wrangler.jsonc against cloudflare/worker.mjs`);
      return;
    }
    if (!env.CRON_SECRET) {
      // The route would answer 401 anyway. Say so where the log is read.
      console.error(`cron: CRON_SECRET is not set; ${path} would reject the call. wrangler secret put CRON_SECRET`);
      return;
    }
    // The hostname is ignored by a service binding; the path is what routes.
    const res = await env.WORKER_SELF_REFERENCE.fetch(`https://altorank-web${path}`, {
      headers: { "x-cron-secret": env.CRON_SECRET },
    });
    const body = (await res.text()).slice(0, 2000);
    console.log(`cron ${path} -> ${res.status} ${body}`);
  },
};

export default worker;
