import { ImageResponse } from "next/og";
import { createServiceClient } from "@/lib/supabase/server";
import { parsePublicDomain } from "@/lib/public-check/domain";
import { loadCachedCheck } from "@/lib/public-check/run";
import { scoreLabel, shortDate } from "@/lib/public-check/shape";

/**
 * Social card for a shared result. Reads the cache only and never crawls:
 * a link preview being generated by a chat app is not a request from the
 * person who shared it, and should not cost the site a fetch. With no cached
 * result the card says so instead of inventing a number.
 */
export const alt = "AI-readiness check by AltoRank";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default async function Image({ params }: { params: Promise<{ domain: string }> }) {
  const { domain: raw } = await params;
  let decoded = raw;
  try {
    decoded = decodeURIComponent(raw);
  } catch {
    // leave as is; the parse below rejects it
  }
  const parsed = parsePublicDomain(decoded);
  const domain = parsed.ok ? parsed.domain : "";
  const data = domain ? await loadCachedCheck(createServiceClient(), domain) : null;

  const measured = data && !data.error && data.score !== null;
  const headline = measured ? String(data.score) : "?";
  const sub = measured
    ? `${scoreLabel(data.score)} · ${data.passed} of ${data.known} checks pass · checked ${shortDate(data.checked_at)}`
    : data?.error
      ? "The site could not be checked"
      : "Not checked yet";

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          padding: 72,
          background: "#fbfaf7",
          color: "#2a2926",
          fontFamily: "sans-serif",
        }}
      >
        <div style={{ display: "flex", flexDirection: "column" }}>
          <div style={{ display: "flex", justifyContent: "space-between", fontSize: 28, color: "#6e6b64" }}>
            <div>Can an AI agent read this site?</div>
            <div>AI-readiness check by AltoRank</div>
          </div>
          <div style={{ fontSize: 64, fontWeight: 700, letterSpacing: -2, marginTop: 12, wordBreak: "break-all" }}>
            {domain || "unknown domain"}
          </div>
        </div>
        <div style={{ display: "flex", flexDirection: "column" }}>
          <div style={{ display: "flex", alignItems: "baseline" }}>
            <div style={{ fontSize: 160, fontWeight: 700, lineHeight: 1, letterSpacing: -6 }}>{headline}</div>
            <div style={{ fontSize: 40, color: "#6e6b64", marginLeft: 12 }}>/100</div>
          </div>
          <div style={{ fontSize: 28, color: "#4a4843", marginTop: 8 }}>{sub}</div>
        </div>
      </div>
    ),
    size,
  );
}
